layout_spectrum: 0.4055415
typography_spectrum: 0.2115216
color:
  saturation: 0.01044264
  lightness: 0.8311951
  brandStrength: 0.8975078
  rhythmicContrast: 0.06524029
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
name: Health
